#!/bin/bash

username="username"
password="password"
host="vpn.host.info"

etc_dir=/etc/ocrc
oc_out="$etc_dir/oc.out"
ping_out="$etc_dir/ping.out"
sudo mkdir -p $etc_dir

ping_host=google.com
ping_deadline=10

connect() {
	echo > $oc_out
	echo $password | sudo openconnect -b -u $username $host --no-dtls &> $oc_out
	[ $(grep 'Failed' $oc_out | wc -l | awk '{print $1}') -gt 0 ] || \
		! [ $(grep 'Connected as' $oc_out | wc -l | awk '{print $1}') -gt 0 ] && \
		reconnect "y"
	connected_as=$(grep 'Connected as' $oc_out --color=never | cut -d',' -f1)
	tput clear
	tput cup 3 5; echo "$connected_as"
	while true; do
		timeout $ping_deadline ping $ping_host &> $ping_out
		[ $(grep -i '\(not\)\|\(resolved\)\|\(known\)' $ping_out | wc -l ) -gt 0 ] || \
			[ $(wc -l $ping_out | awk '{print $1}') -le 1 ] && \
			reconnect "y"
		avg_ping=$(grep 'time=' $ping_out | rev | cut -d'=' -f1 | rev | cut -d'm' -f1 | awk '{sum+=$1; n++} END {print sum/n}' | cut -d'.' -f1)
		tput clear; tput cup 5 5; echo "ping $ping_host ${avg_ping}ms"
	done
}

disconnect() {
	sudo pkill -SIGINT openconnect
}

reconnect() {
	disconnect
	sleep 1
	if [ -z $1 ]; then echo; read -p "RECONNECT? [Y/n]: " comm;
	else comm="$1"; fi
	case $comm in
		[nN]* ) exit ;;
		* ) connect ;;
	esac
}

trap reconnect SIGINT
connect

